<a href="https://colab.research.google.com/github/AndrewInterino/LinearAlg2021-2022/blob/main/Assignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear ALgrebra for ECE
## Laboratory 6 : Matrix Operation


### Objective
At the end of this activity you will be able to :
1. Be familiar with the fundamentdal matrix operations
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

### Discussion 

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

## Tranpostion

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$A^T$

In [5]:
A = np.array([
              [1,-2,5],
              [5,-1,0],
              [0,-3,3]
])
A

array([[ 1, -2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [4]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [-2, -1, -3],
       [ 5,  0,  3]])

In [6]:
AT2= A.T
AT2

array([[ 1,  5,  0],
       [-2, -1, -3],
       [ 5,  0,  3]])

In [7]:
np.array_equiv(AT1, AT2)

True

In [8]:
B = np.array([
              [1,2,3,4],
              [1,0,2,1]
])
B.shape

(2, 4)

In [9]:
np.transpose(B).shape

(4, 2)

In [10]:
B.T.shape

(4, 2)

### Try to create your own matrix

In [13]:
UWU = np.array([
                [6,-2,1],
                [7,9,8],
                [-8,5,-1]
])

In [18]:
UWU.T


array([[ 6,  7, -8],
       [-2,  2,  5],
       [ 1,  8, -1]])

In [19]:
UWU.shape

(3, 3)

In [20]:
UWU.T.shape

(3, 3)

## Dot Product

In [21]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [22]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [23]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [24]:
X@Y

array([[3, 4],
       [2, 2]])

In [26]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

### Try

In [27]:
Boy = np.array([
    [3,2,6],
    [1,5,7],
    [3,6,8]
])
Girl = np.array([
    [7,9,2],
    [2,4,6],
    [6,2,4]
])

In [28]:
np.dot(Boy,Girl)

array([[61, 47, 42],
       [59, 43, 60],
       [81, 67, 74]])

In [30]:
Boy.dot(Girl)

array([[61, 47, 42],
       [59, 43, 60],
       [81, 67, 74]])

In [29]:
Boy@Girl

array([[61, 47, 42],
       [59, 43, 60],
       [81, 67, 74]])

In [31]:
np.matmul(Boy,Girl)

array([[61, 47, 42],
       [59, 43, 60],
       [81, 67, 74]])

### Rule 1

In [32]:
A = np.array([
              [2,4],
              [5,-2],
              [0,1]           
])
B = np.array([
              [1,1],
              [3,3],
              [-1,-2]
])
C = np.array([
              [0,1,1],
              [1,1,2]
])


In [33]:
A@C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [34]:
B@C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

In [35]:
A@B

ValueError: ignored

In [36]:
A@B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [37]:
XX = np.array([
               [1,2,3,0]
])
YY = np.array([
               [1,0,4,-1]
])

In [38]:
YY.T@XX

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [40]:
XX@YY.T

array([[13]])

### Rule 2

In [41]:
AA = np.array([
                 [2,5,3],
                 [6,8,2],
                 [1,5,8]
])
BB = np.array([
               [4,2,4],
               [7,0,3],
               [2,4,1]
])
CC = np.array([
               [2,4,7],
               [8,3,0],
               [0,2,5]
])

In [56]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.array_equal(AA@BB, BB@AA)

False

In [49]:
np.array_equiv(G1,G2)

True

In [47]:
G1= AA*BB

In [48]:
G2= BB*AA

In [53]:
np.array_equiv(G3,G4)

True

In [50]:
G3= AA*(BB*CC)

In [52]:
G4= (AA*BB)*CC

In [57]:
AA.dot(np.eye(3))

array([[2., 5., 3.],
       [6., 8., 2.],
       [1., 5., 8.]])

##Determinant

In [58]:
D = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(D)

3.0000000000000004

In [59]:
E= np.array([
             [1,5,2],
             [3,-1,-1],
             [0,-2,1]
])
np.linalg.det(E)

-30.000000000000014

## Inverse

In [60]:
M = np.array([
              [1,7],
              [-3,5]
])
np.array(M@ np.linalg.inv(M),dtype=int)

array([[1, 0],
       [0, 1]])

In [64]:
P = np.array([
              [6,9,0],
              [4,2,-1],
              [3,6,7]
])
Q= np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [67]:
np.array(P@Q,dtype=int)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [66]:
np.array(P@Q)

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])