<a href="https://colab.research.google.com/github/AndrewInterino/LinearAlg2021-2022/blob/main/Assignment6needflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear ALgrebra for ECE
## Laboratory 6 : Matrix Operation


### Objective
At the end of this activity you will be able to :
1. Be familiar with the fundamentdal matrix operations
2. Apply the operations to solve intermediate equations.
3. Apply matrix algebra in engineering solutions.

### Discussion 

In [1]:
import numpy as np 
import matplotlib.pyplot as plt
%matplotlib inline

## Tranpostion
One of the fundamental operations in matrix algebra is Transposition. The transpose of a matrix is done by flipping the values of its elements over its diagonals. With this, the rows and columns from the original matrix will be switched. So for a matrix  A  its transpose is denoted as  AT . So for example:

$$A = \begin{bmatrix} 1 & 2 & 5\\5 & -1 &0 \\ 0 & -3 & 3\end{bmatrix} $$

$$ A^T = \begin{bmatrix} 1 & 5 & 0\\2 & -1 &-3 \\ 5 & 0 & 3\end{bmatrix}$$

In [ ]:
A = np.array([
              [1,-2,5],
              [5,-1,0],
              [0,-3,3]
])
A

array([[ 1, -2,  5],
       [ 5, -1,  0],
       [ 0, -3,  3]])

In [ ]:
AT1 = np.transpose(A)
AT1

array([[ 1,  5,  0],
       [-2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
AT2= A.T
AT2

array([[ 1,  5,  0],
       [-2, -1, -3],
       [ 5,  0,  3]])

In [ ]:
np.array_equiv(AT1, AT2)

True

In [ ]:
B = np.array([
              [1,2,3,4],
              [1,0,2,1]
])
B.shape

(2, 4)

In [ ]:
np.transpose(B).shape

(4, 2)

In [ ]:
B.T.shape

(4, 2)

### Try to create your own matrix

In [ ]:
UWU = np.array([
                [6,-2,1],
                [7,9,8],
                [-8,5,-1]
])

In [ ]:
UWU.T


array([[ 6,  7, -8],
       [-2,  2,  5],
       [ 1,  8, -1]])

In [ ]:
UWU.shape

(3, 3)

In [ ]:
UWU.T.shape

(3, 3)

## Dot Product
If you recall the dot product from laboratory activity before, we will try to implement the same operation with matrices. In matrix dot product we are going to get the sum of products of the vectors by row-column pairs. So if we have two matrices $X$ and $Y$:

$$X = \begin{bmatrix}x_{(0,0)}&x_{(0,1)}\\ x_{(1,0)}&x_{(1,1)}\end{bmatrix}, Y = \begin{bmatrix}y_{(0,0)}&y_{(0,1)}\\ y_{(1,0)}&y_{(1,1)}\end{bmatrix}$$

The dot product will then be computed as:
$$X \cdot Y= \begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} \\  x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)}
\end{bmatrix}$$

So if we assign values to $X$ and $Y$:
$$X = \begin{bmatrix}1&2\\ 0&1\end{bmatrix}, Y = \begin{bmatrix}-1&0\\ 2&2\end{bmatrix}$$

$$X \cdot Y= \begin{bmatrix} 1*-1 + 2*2 & 1*0 + 2*2 \\  0*-1 + 1*2 & 0*0 + 1*2 \end{bmatrix} = \begin{bmatrix} 3 & 4 \\2 & 2 \end{bmatrix}$$
This could be achieved programmatically using `np.dot()`, `np.matmul()` or the `@` operator.

In [ ]:
X = np.array([
    [1,2],
    [0,1]
])
Y = np.array([
    [-1,0],
    [2,2]
])

In [ ]:
np.dot(X,Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X.dot(Y)

array([[3, 4],
       [2, 2]])

In [ ]:
X@Y

array([[3, 4],
       [2, 2]])

In [ ]:
np.matmul(X,Y)

array([[3, 4],
       [2, 2]])

### Try 2

In [ ]:
Boy = np.array([
    [3,2,6],
    [1,5,7],
    [3,6,8]
])
Girl = np.array([
    [7,9,2],
    [2,4,6],
    [6,2,4]
])

In [ ]:
np.dot(Boy,Girl)

array([[61, 47, 42],
       [59, 43, 60],
       [81, 67, 74]])

In [ ]:
Boy.dot(Girl)

array([[61, 47, 42],
       [59, 43, 60],
       [81, 67, 74]])

In [ ]:
Boy@Girl

array([[61, 47, 42],
       [59, 43, 60],
       [81, 67, 74]])

In [ ]:
np.matmul(Boy,Girl)

array([[61, 47, 42],
       [59, 43, 60],
       [81, 67, 74]])

In matrix dot products there are additional rules compared with vector dot products. Since vector dot products were just in one dimension there are less restrictions. Since now we are dealing with Rank 2 vectors we need to consider some rules:

### Rule 1: The inner dimensions of the two matrices in question must be the same. 

So given a matrix $A$ with a shape of $(a,b)$ where $a$ and $b$ are any integers. If we want to do a dot product between $A$ and another matrix $B$, then matrix $B$ should have a shape of $(b,c)$ where $b$ and $c$ are any integers. So for given the following matrices:

$$A = \begin{bmatrix}2&4\\5&-2\\0&1\end{bmatrix}, B = \begin{bmatrix}1&1\\3&3\\-1&-2\end{bmatrix}, C = \begin{bmatrix}0&1&1\\1&1&2\end{bmatrix}$$

So in this case $A$ has a shape of $(3,2)$, $B$ has a shape of $(3,2)$ and $C$ has a shape of $(2,3)$. So the only matrix pairs that is eligible to perform dot product is matrices $A \cdot C$, or $B \cdot C$.  

In [ ]:
A = np.array([
              [2,4],
              [5,-2],
              [0,1]           
])
B = np.array([
              [1,1],
              [3,3],
              [-1,-2]
])
C = np.array([
              [0,1,1],
              [1,1,2]
])


In [ ]:
A@C

array([[ 4,  6, 10],
       [-2,  3,  1],
       [ 1,  1,  2]])

In [ ]:
B@C

array([[ 1,  2,  3],
       [ 3,  6,  9],
       [-2, -3, -5]])

In [ ]:
A@B

In [ ]:
A@B.T

array([[  6,  18, -10],
       [  3,   9,  -1],
       [  1,   3,  -2]])

In [ ]:
XX = np.array([
               [1,2,3,0]
])
YY = np.array([
               [1,0,4,-1]
])

In [ ]:
YY.T@XX

array([[ 1,  2,  3,  0],
       [ 0,  0,  0,  0],
       [ 4,  8, 12,  0],
       [-1, -2, -3,  0]])

In [ ]:
XX@YY.T

array([[13]])

### Rule 2: Dot Product has special properties

Dot products are prevalent in matrix algebra, this implies that it has several unique properties and it should be considered when formulation solutions:
 1. $A \cdot B \neq B \cdot A$
 2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
 5. $A\cdot I = A$
 6. $A\cdot \emptyset = \emptyset$ 

In [2]:
AA = np.array([
                 [2,5,3],
                 [6,8,2],
                 [1,5,8]
])
BB = np.array([
               [4,2,4],
               [7,0,3],
               [2,4,1]
])
CC = np.array([
               [2,4,7],
               [8,3,0],
               [0,2,5]
])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.array_equal(AA@BB, BB@AA)
#1

False

In [7]:
G1 = AA*(BB*CC)
#2

In [8]:
G2 = (AA*BB)*CC

In [9]:
np.array_equiv(G1,G2)

True

In [ ]:
np.array_equiv(G3,G4)

True

In [ ]:
G3= AA*(BB*CC)

In [ ]:
G4= (AA*BB)*CC

In [10]:
G5 = (BB+CC)@AA
#4

In [11]:
G6 = (BB@AA)+(CC@AA)

In [12]:
np.array_equiv(G5,G6)

True

In [13]:
AA.dot(np.eye(3))
#5

array([[2., 5., 3.],
       [6., 8., 2.],
       [1., 5., 8.]])

In [20]:
z_mat = np.zeros(AA.shape)
z_mat
#6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
a_dot_z = AA.dot(np.zeros(AA.shape))
a_dot_z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.array_equal(a_dot_z,z_mat)

True

##Determinant
A determinant is a scalar value derived from a square matrix. The determinant is a fundamental and important value used in matrix algebra. Although it will not be evident in this laboratory on how it can be used practically, but it will be reatly used in future lessons.

The determinant of some matrix $A$ is denoted as $det(A)$ or $|A|$. So let's say $A$ is represented as:
$$A = \begin{bmatrix}a_{(0,0)}&a_{(0,1)}\\a_{(1,0)}&a_{(1,1)}\end{bmatrix}$$
We can compute for the determinant as:
$$|A| = a_{(0,0)}*a_{(1,1)} - a_{(1,0)}*a_{(0,1)}$$
So if we have $A$ as:
$$A = \begin{bmatrix}1&4\\0&3\end{bmatrix}, |A| = 3$$

But you might wonder how about square matrices beyond the shape $(2,2)$? We can approach this problem by using several methods such as co-factor expansion and the minors method. This can be taught in the lecture of the laboratory but we can achieve the strenuous computation of high-dimensional matrices programmatically using Python. We can achieve this by using `np.linalg.det()`.

In [ ]:
D = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(D)

3.0000000000000004

In [ ]:
E= np.array([
             [1,5,2],
             [3,-1,-1],
             [0,-2,1]
])
np.linalg.det(E)

-30.000000000000014

## Inverse

The inverse of a matrix is another fundamental operation in matrix algebra. Determining the inverse of a matrix let us determine if its solvability and its characteristic as a system of linear equation — we'll expand on this in the nect module. Another use of the inverse matrix is solving the problem of divisibility between matrices. Although element-wise division exists but dividing the entire concept of matrices does not exists. Inverse matrices provides a related operation that could have the same concept of "dividing" matrices.

Now to determine the inverse of a matrix we need to perform several steps. So let's say we have a matrix $M$:
$$M = \begin{bmatrix}1&7\\-3&5\end{bmatrix}$$
First, we need to get the determinant of $M$.
$$|M| = (1)(5)-(-3)(7) = 26$$
Next, we need to reform the matrix into the inverse form:
$$M^{-1} = \frac{1}{|M|} \begin{bmatrix} m_{(1,1)} & -m_{(0,1)} \\ -m_{(1,0)} & m_{(0,0)}\end{bmatrix}$$
So that will be:
$$M^{-1} = \frac{1}{26} \begin{bmatrix} 5 & -7 \\ 3 & 1\end{bmatrix} = \begin{bmatrix} \frac{5}{26} & \frac{-7}{26} \\ \frac{3}{26} & \frac{1}{26}\end{bmatrix}$$
For higher-dimension matrices you might need to use co-factors, minors, adjugates, and other reduction techinques. To solve this programmatially we can use `np.linalg.inv()`.

In [ ]:
M = np.array([
              [1,7],
              [-3,5]
])
np.array(M@ np.linalg.inv(M),dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
P = np.array([
              [6,9,0],
              [4,2,-1],
              [3,6,7]
])
Q= np.linalg.inv(P)
Q

array([[-0.12578616,  0.39622642,  0.05660377],
       [ 0.19496855, -0.26415094, -0.03773585],
       [-0.11320755,  0.05660377,  0.1509434 ]])

In [ ]:
np.array(P@Q,dtype=int)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]])

In [ ]:
np.array(P@Q)

array([[ 1.00000000e+00, -5.55111512e-17, -6.93889390e-18],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [ 2.77555756e-17, -1.38777878e-17,  1.00000000e+00]])

## Activity 

### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [23]:
HH = np.array([
                 [4,6,2],
                 [1,5,4],
                 [3,2,6]
])
JJ = np.array([
               [3,5,8],
               [7,2,5],
               [0,1,9]
])
RR = np.array([
               [4,2,6],
               [7,8,2],
               [1,0,3]
])

In [24]:
#1
np.array_equal(HH@JJ, JJ@HH)

False

In [25]:
#2
np.array_equiv(HH@(JJ@RR),(HH@JJ)@RR)

True

In [26]:
#3
np.array_equiv(HH@(JJ+RR),(HH@JJ)+(HH@RR))

True

In [ ]:
#4
G5 = (BB+CC)@AA

In [ ]:
G6 = (BB@AA)+(CC@AA)

In [28]:
np.array_equiv((JJ+RR)@HH,(JJ@HH)+(RR@HH))

True

In [29]:
#5
HH.dot(np.eye(3))

array([[4., 6., 2.],
       [1., 5., 4.],
       [3., 2., 6.]])

In [30]:
#6
z_math = np.zeros(HH.shape)

In [31]:
h_dot_z = HH.dot(np.zeros(HH.shape))

In [33]:
np.array_equal(h_dot_z,z_math)

True

## Conclusion

For your conclusion synthesize the concept and application of the laboratory. Briefly discuss what you have learned and achieved in this activity.

Based on the experiment with the help of Google collab and Python, we were able to practice such fundamental operations. Such as Transpose, which switches the position of the rows and columns. Then Dot Product is the sum product of the vectors within the matrix. The Determinant is an operation that requires a matrix into a square matrix for it to be able to find the wanted answer. Finally, Inverse which can determine whether a matrix is solvable or not and identify its characteristic as a system of linear equation.