<a href="https://colab.research.google.com/github/AndrewInterino/LinearAlg2021-2022/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra for ECE
## Laboratory 4 : Matrices 

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. $$

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}
$$

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

In [5]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [6]:
A = np.array([
          [1, 2],
          [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [9]:
G = np.array([
              [1,1],
              [3,1]
])
describe_mat(G)

Matrix:
[[1 1]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [13]:
B = np.array([
              [4,5],
              [3,2],
              [9,7]
])
describe_mat(B)

Matrix:
[[4 5]
 [3 2]
 [9 7]]

Shape:	(3, 2)
Rank:	2



In [14]:
H = np.array([1, 5, 6, 4, 8])
describe_mat(H)

Matrix:
[1 5 6 4 8]

Shape:	(5,)
Rank:	1



In [15]:
row_mat_1D = np.array([
                       1,2,3
])
row_mat_2D = np.array([
                       [1,3,2]
])
describe_mat(row_mat_1D)
describe_mat(row_mat_2D)

Matrix:
[1 2 3]

Shape:	(3,)
Rank:	1

Matrix:
[[1 3 2]]

Shape:	(1, 3)
Rank:	2



In [16]:
col_mat = np.array([
                  [1],
                  [2],
                  [3]       
])
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [3]]

Shape:	(3, 1)
Rank:	2



In [18]:
### Square matrices
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [19]:
## Null martix
def describe_mat(matrix):
  if matrix.size > 0:
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
  else:
    print('Matrix is Null')

In [22]:
## Zero Matrix
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
#One Matrix
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'ones Row Matrix: \n{ones_mat_row}')
print(f'ones Square Matrix: \n{ones_mat_sqr}')
print(f'onesRectangular Matrix: \n{ones_mat_rct}')

ones Row Matrix: 
[[1. 1.]]
ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
onesRectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
## Diagonal Matrix
np.array([
          [2,0,0],
          [0,3,0],
          [0,0,5]
])

In [24]:
d = np.diag([2,3,5,7,2,5])
d

array([[2, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 5]])

In [26]:
## Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
## Upper Triangular Matrix


In [ ]:
## Lower Triangular Matrix

In [28]:
## Practice 1
theta = np.array([
          [5, 3, -1]
])
describe_mat(theta)

Matrix:
[[ 5  3 -1]]

Shape:	(1, 3)
Rank:	2
Is Square: False



In [31]:
## Practice 2
A = np.array([
          [1, 2, 1],
          [0, 4, -1],
          [0, 0, 10]

])
describe_mat(A)

Matrix:
[[ 1  2  1]
 [ 4  0 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



In [43]:
## Practice 3
$$
G = \left\{
    \begin{array}\
        x + 7x_2+8x_3\\ 
        2x + 2x_2+2x_3\\
        4x+6x_2+7x_3
    \end{array}
\right. \\
$$

SyntaxError: ignored

In [ ]:
## practice 4


Matrix

In [44]:
## Matrix Algrabra
## addition
A = np.array([
              [1,2],
              [2,3],
              [4,1]
])
B = np.array([
              [2,2],
              [0,0],
              [1,1]
])
A+B

array([[3, 4],
       [2, 3],
       [5, 2]])

In [45]:
### Broadcasting
2+A

array([[3, 4],
       [4, 5],
       [6, 3]])

In [46]:
## Subtraction
A-B

array([[-1,  0],
       [ 2,  3],
       [ 3,  0]])

In [47]:
### Broadcasting 
3-B

array([[1, 1],
       [3, 3],
       [2, 2]])

In [48]:
## Element-wise Multiplication
A*B

array([[2, 4],
       [0, 0],
       [4, 1]])

In [49]:
### broadcasting
2*A

array([[2, 4],
       [4, 6],
       [8, 2]])

In [50]:
## DIvision
A/B

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([[0.5, 1. ],
       [inf, inf],
       [4. , 1. ]])

In [51]:
alpha = 10**-10
A/(alpha+B)

array([[5.e-01, 1.e+00],
       [2.e+10, 3.e+10],
       [4.e+00, 1.e+00]])