<a href="https://colab.research.google.com/github/AndrewInterino/LinearAlg2021-2022/blob/main/prelimsolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np 

def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')



In [5]:
A = np.array([[8, 2],
              [5, 2],
              [1, 1]
              ])
describe_mat(A)

Matrix:
[[8 2]
 [5 2]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [6]:
X = np.array([[1, -5, 4],
              [4, -1, 5],
              [3, -1, -6]
              ])
Y = np.triu(X)
Y

array([[ 5,  0,  4],
       [ 0, -1,  5],
       [ 0,  0, -6]])

int1 = 10
int2 = 6
if int1 != int2:


In [7]:
int1 = 10
int2 = 6
if int1 != int2:
  int2 = ++int2
  print(int1-int2)

4


In [26]:
d = {0, 1, 2}
for x in d:
  print(x)

0
1
2


In [9]:
def create_user (userid):
  print("success: {}".format(userid))

In [11]:
userid = 2021_10001
create_user(2021-100100)

success: -98079


In [14]:
import numpy as np 

a = np.array([1,2,3,5,8])
b = np.array([0,3,4,2,1])
c = a + b
c

array([1, 5, 7, 7, 9])

In [15]:
x, y, z = 2, 4.0, '3'
type(z)

str

In [17]:
import numpy as np 

f = np.array([[1,2,3],[0,1,4]])
print (f.shape)

(2, 3)


In [19]:
i = 0
while i < 5:
  print(i)
  i += 1
  if i == 3:
    break
else:
  print(0)

0
1
2


In [20]:
P = np.array([[5,7,2],
              [2,3,3],
              [4,1,0]
              ])
Q = np.array([[2,2,-3],
              [0,0,1],
              [1,1,-3]
              ])
P + 2*Q

array([[ 9, 11, -4],
       [ 2,  3,  5],
       [ 6,  3, -6]])

In [21]:
R = np.array([[2,0,-1],
              [4,-5,2]
              ])
T = np.array([[7,-5,1],
              [1,-4,-3]
              ])
T - 2*R

array([[ 3, -5,  3],
       [-7,  6, -7]])

In [25]:
u = 1
while True:
  if u % 5 == 0:
      break
  print(u)
  u + = 1

SyntaxError: ignored